### ISSUE TITLE
Test command failed due to absence of required test files in respective project directories

### ISSUE THREAD

**Issue by abdullahfarwees** [mozilla/mp4parse-rust#412]
**Steps to reproduce:**
1. open terminal (in Ubuntu 22LTS) and navigate to project folder and build the project.
2. Enter the command _cargo test_ 
3. Below panic appears  which stating FileNotFound 

**Expected behaviour**
All test cases should pass if it have the respective test files

**Actual behaviour**
3 test cases failed due to unavailability of test files in the respective file locations

**Details of error**

**kind: NotFound, message: "No such file or directory"**

---- public_avif_grid stdout ----
thread 'public_avif_grid' panicked at 'av1-avif/testFiles/Microsoft/Summer_in_Tomsk_720p_5x4_grid.avif: Os { code: 2, kind: NotFound, message: "No such file or directory" }', mp4parse/tests/public.rs:1225:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- public_avif_read_samples stdout ----
thread 'public_avif_read_samples' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:166:5

---- public_avis_major_no_pitm stdout ----
thread 'public_avis_major_no_pitm' panicked at 'Unknown file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', mp4parse/tests/public.rs:1235:58
failures:
    public_avif_grid
    public_avif_read_samples
    public_avis_major_no_pitm

test result: FAILED. 58 passed; 3 failed; 1 ignored; 0 measured; 0 filtered out; finished in 28.22s

error: test failed, to rerun pass `-p mp4parse --test public`

**Comment by SingingTree** [comment]
Some of the tests rely on files from git submodules, which is the case for the files above. If you run the following commands
```
git submodule init
```
followed by
```
git submodule update
```
in `mp4parse_rust/mp4parse/av1-avif` and `mp4parse_rust/mp4parse/av1-avi/link-u-avif-sample-images` does that resolve the test failures?
